# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_auto_20170508_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstage',
            options={'ordering': ['ordering']},
        ),
    ]
